;; Generated by lk exercises from clojure/src/lesson04/aggregation.clj. DO NOT EDIT;
;; edit the reference lesson and regenerate. Fill in the TODOs here.

(ns exercises.lesson04.aggregation
  "Lesson 4 — aggregation and sorting.

  GROUP BY has two classic implementations:

  - hash aggregate: one hash table entry per group, holding running accumulators. Reads its input
    once in any order; memory grows with the number of groups. A pipeline breaker: no group is
    final until the input ends.
  - sort aggregate: if the input is sorted by the group keys, groups arrive contiguously, so keep
    ONE accumulator and emit it when the key changes. Streams, constant memory — but someone has
    to sort first.

  Sorting is the other big pipeline breaker:

  - sort: read everything, sort in memory.
  - external sort: when everything doesn't fit, sort fixed-size runs, \"spill\" each run, then
    k-way merge the runs with a priority queue. (Here the runs stay in memory — the algorithm is
    the point, not the disk.)
  - top-N: ORDER BY … LIMIT n only needs the best n rows; keep them in a bounded heap and never
    sort the rest."
  (:require [clojure.string :as str])
  (:import [java.util PriorityQueue Comparator]))

;;; ------------------------------------------------------------------------------------------------
;;; Values, expressions, operators — compact copies (lessons are standalone)

(defn compare-values [a b]
  (if (and (number? a) (number? b))
    (if (and (int? a) (int? b)) (compare (long a) (long b)) (compare (double a) (double b)))
    (compare a b)))

(defn- col-index [schema col-name]
  (let [exact (keep-indexed (fn [i c] (when (= c col-name) i)) schema)
        bare  (keep-indexed (fn [i c] (when (str/ends-with? c (str "." col-name)) i)) schema)]
    (cond (seq exact) (first exact)
          (= 1 (count bare)) (first bare)
          :else (throw (ex-info (str "unknown or ambiguous column " col-name) {:schema schema})))))

(defn compile-expr [expr schema]
  (let [[tag a b] expr
        sub #(compile-expr % schema)]
    (case tag
      :col (let [i (col-index schema a)] (fn [row] (nth row i)))
      :lit (fn [_] a)
      (:+ :- :*) (let [l (sub a) r (sub b) op ({:+ + :- - :* *} tag)]
                   (fn [row] (let [x (l row) y (r row)]
                               (when (and (some? x) (some? y))
                                 (if (and (int? x) (int? y)) (op x y) (op (double x) (double y))))))))))

(defprotocol Operator
  (open! [op]) (next! [op]) (close! [op]) (schema [op]))

(defn run [op]
  (open! op)
  (try (loop [acc []] (if-let [r (next! op)] (recur (conj acc r)) acc))
       (finally (close! op))))

(defn scan [{:keys [columns rows]} alias]
  (let [pos (volatile! 0)]
    (reify Operator
      (open! [_] (vreset! pos 0))
      (next! [_] (when (< @pos (count rows)) (let [r (nth rows @pos)] (vswap! pos inc) r)))
      (close! [_] nil)
      (schema [_] (mapv #(str alias "." %) columns)))))

(defn- from-seq
  "An operator over an in-memory sequence of rows — how pipeline breakers hand their results back."
  [rows out-schema]
  (let [remaining (volatile! nil)]
    (reify Operator
      (open! [_] (vreset! remaining (seq rows)))
      (next! [_] (when-let [[r & more] @remaining] (vreset! remaining more) r))
      (close! [_] (vreset! remaining nil))
      (schema [_] out-schema))))

;;; ------------------------------------------------------------------------------------------------
;;; Aggregate functions: init / step / finish over plain-data accumulators

(defn- agg-init [_] {:count 0 :sum nil :min nil :max nil})

(defn- agg-step
  "Fold one input value into the accumulator. `count(*)` passes ::star so every row counts."
  [acc v]
  (cond
    (= v ::star) (update acc :count inc)
    (nil? v)     acc                                   ; aggregates skip NULLs
    :else (-> acc
              (update :count inc)
              (update :sum #(cond (nil? %) v
                                  (and (int? %) (int? v)) (+ % v)
                                  :else (+ (double %) (double v))))
              (update :min #(if (or (nil? %) (neg? (compare-values v %))) v %))
              (update :max #(if (or (nil? %) (pos? (compare-values v %))) v %)))))

(defn- agg-finish [fname {:keys [count sum min max]}]
  (case fname
    "count" count
    "sum"   sum
    "min"   min
    "max"   max
    "avg"   (when (pos? count) (/ (double sum) count))))

(defn- agg-fns
  "Compile agg specs [{:fn \"sum\" :arg expr :name \"total\"} …]; :arg :* means count(*)."
  [aggs in-schema]
  (mapv (fn [{:keys [arg]}] (if (= arg :*) (constantly ::star) (compile-expr arg in-schema))) aggs))

;;; ------------------------------------------------------------------------------------------------
;;; Hash aggregate

(defn hash-aggregate
  "GROUP BY `group-exprs` computing `aggs`. One accumulator vector per group, found by hashing the
  group key. Groups come out in first-seen order (a map from key → slot plus an ordered vector —
  never iterate the hash table itself, its order is arbitrary). With no group keys, an empty input
  still produces one row: SELECT count(*) FROM empty → 0."
  [child group-exprs aggs]
  (let [in        (schema child)
        keys-f    (mapv #(compile-expr % in) group-exprs)
        vals-f    (agg-fns aggs in)
        out-names (into (mapv (fn [e] (if (= :col (first e)) (second e) (pr-str e))) group-exprs)
                        (map :name aggs))
        result    (volatile! nil)]
    (reify Operator
      (open! [_]
        (open! child)
        ;; EXERCISE(hash-aggregate): Drain the child. For each row compute its group key, find (or create) that group's accumulators, and step each one with its aggregate's input value. Then close the child and put the finished rows (key ++ finalized aggregates) in @result, in first-seen order. No GROUP BY and no input still yields one row.
        (throw (ex-info "TODO: exercise hash-aggregate" {:exercise "hash-aggregate"}))
        )
      (next! [_] (when-let [[r & more] @result] (vreset! result more) r))
      (close! [_] (vreset! result nil))
      (schema [_] out-names))))

;;; ------------------------------------------------------------------------------------------------
;;; Sort aggregate

(defn sort-aggregate
  "Like hash-aggregate, but the input must already be sorted by the group keys. Keeps one group's
  accumulators at a time and emits it when the key changes: streaming, O(1) memory."
  [child group-exprs aggs]
  (let [in        (schema child)
        keys-f    (mapv #(compile-expr % in) group-exprs)
        vals-f    (agg-fns aggs in)
        out-names (into (mapv (fn [e] (if (= :col (first e)) (second e) (pr-str e))) group-exprs)
                        (map :name aggs))
        current   (volatile! nil)    ; [key accs] of the group being accumulated
        done?     (volatile! false)
        emit      (fn [[k accs]] (into k (map #(agg-finish (:fn %1) %2) aggs accs)))]
    (reify Operator
      (open! [_] (open! child) (vreset! current nil) (vreset! done? false))
      (next! [_]
        (loop []
          (when-not @done?
            (if-let [row (next! child)]
              (let [k (mapv #(% row) keys-f)
                    step (fn [accs] (mapv (fn [acc f] (agg-step acc (f row))) accs vals-f))]
                (cond
                  (nil? @current)        (do (vreset! current [k (step (mapv agg-init aggs))]) (recur))
                  (= k (first @current)) (do (vswap! current update 1 step) (recur))
                  :else                  (let [finished @current]       ; key changed: emit
                                           (vreset! current [k (step (mapv agg-init aggs))])
                                           (emit finished))))
              (do (vreset! done? true)
                  (cond @current (emit @current)
                        (empty? group-exprs) (emit [[] (mapv agg-init aggs)])
                        :else nil))))))
      (close! [_] (close! child))
      (schema [_] out-names))))

;;; ------------------------------------------------------------------------------------------------
;;; Sorting

(defn row-comparator
  "Comparator over rows for sort keys [[key-fn :asc|:desc] …]. NULLs sort last in both directions.
  Counts comparisons in `counter` when given."
  ([key-specs] (row-comparator key-specs nil))
  ([key-specs counter]
   (fn [a b]
     (when counter (swap! counter inc))
     (reduce (fn [_ [f dir]]
               (let [x (f a) y (f b)
                     c (cond (and (nil? x) (nil? y)) 0
                             (nil? x) 1                  ; NULLs last…
                             (nil? y) -1                 ; …regardless of direction
                             :else (cond-> (compare-values x y) (= dir :desc) -))]
                 (if (zero? c) 0 (reduced c))))
             0 key-specs))))

(defn- compile-keys [keys in] (mapv (fn [[e dir]] [(compile-expr e in) (or dir :asc)]) keys))

(defn sort-op
  "Read everything, sort in memory (stable), emit. `keys` = [[expr :asc|:desc] …]."
  [child keys & [{:keys [counter]}]]
  (let [cmp (row-comparator (compile-keys keys (schema child)) counter)
        out (volatile! nil)]
    (reify Operator
      (open! [_] (vreset! out (seq (sort cmp (run child)))))
      (next! [_] (when-let [[r & more] @out] (vreset! out more) r))
      (close! [_] (vreset! out nil))
      (schema [_] (schema child)))))

(defn external-sort
  "Sort with bounded memory: cut the input into runs of `run-size` rows, sort each run (in a real
  engine: write it to disk), then merge all runs at once with a priority queue holding the head
  row of each run. Memory during the merge: one row per run. `stats` gets :runs and :heap-pops."
  [child keys run-size & [{:keys [stats]}]]
  (let [cmp   (row-comparator (compile-keys keys (schema child)))
        heap  (volatile! nil)    ; PriorityQueue of [row run-index position]
        runs  (volatile! [])]
    (reify Operator
      (open! [_]
        ;; phase 1: produce sorted runs
        (open! child)
        (vreset! runs
                 (loop [runs []]
                   (let [chunk (loop [chunk []]
                                 (if (< (count chunk) run-size)
                                   (if-let [r (next! child)] (recur (conj chunk r)) chunk)
                                   chunk))]
                     (if (empty? chunk) runs (recur (conj runs (vec (sort cmp chunk))))))))
        (close! child)
        (some-> stats (swap! assoc :runs (count @runs)))
        ;; phase 2: seed the heap with the first row of every run. Ties break on run index so the
        ;; merge is stable (earlier runs hold earlier input rows).
        (let [pq (PriorityQueue. (max 1 (count @runs))
                                 (reify Comparator
                                   (compare [_ [ra ia] [rb ib]]
                                     (let [c (cmp ra rb)] (if (zero? c) (compare ia ib) c)))))]
          (doseq [[i run] (map-indexed vector @runs)]
            (.add pq [(first run) i 0]))
          (vreset! heap pq)))
      (next! [_]
        ;; EXERCISE(external-sort-merge): The heap holds [row run-index position] for the head of each run. Take the smallest, push the next row from the same run (if any), and return the row taken. Count :heap-pops in `stats`.
        (throw (ex-info "TODO: exercise external-sort-merge" {:exercise "external-sort-merge"}))
        )
      (close! [_] (vreset! heap nil) (vreset! runs []))
      (schema [_] (schema child)))))

(defn top-n
  "ORDER BY keys LIMIT n without sorting everything: keep the best n rows seen so far in a heap
  whose head is the WORST of them. Each new row either loses to the head (discard) or replaces it.
  O(rows · log n) and O(n) memory."
  [child keys n & [{:keys [counter]}]]
  (let [cmp (row-comparator (compile-keys keys (schema child)) counter)
        out (volatile! nil)]
    (reify Operator
      (open! [_]
        (open! child)
        ;; entries are [row seq-no]; seq-no makes ties deterministic (earlier row wins)
        (let [worst-first (reify Comparator
                            (compare [_ [ra sa] [rb sb]]
                              (let [c (cmp rb ra)] (if (zero? c) (compare sb sa) c))))
              pq (PriorityQueue. (max 1 n) worst-first)]
          ;; EXERCISE(top-n): Read every child row as [row seq-no]. Keep at most n entries in `pq`, whose head is the worst kept: fill it up, then replace the head only when a new row is strictly better.
          (throw (ex-info "TODO: exercise top-n" {:exercise "top-n"}))
          (close! child)
          (vreset! out (seq (map first (sort (fn [a b] (.compare worst-first b a)) (vec pq)))))))
      (next! [_] (when-let [[r & more] @out] (vreset! out more) r))
      (close! [_] (vreset! out nil))
      (schema [_] (schema child)))))

;;; ------------------------------------------------------------------------------------------------
;;; Data

(def toy-orders
  {:columns ["id" "customer_id" "product_id" "qty"]
   :rows    [[10 1 100 2] [11 1 101 1] [12 3 100 5] [13 4 102 1] [14 9 101 3]]})

(defn lcg [seed]
  (let [state (volatile! (long seed))]
    (fn intn [n]
      (vswap! state #(unchecked-add (unchecked-multiply % 6364136223846793005) 1442695040888963407))
      (mod (unsigned-bit-shift-right @state 33) n))))

(defn generate-orders
  "The 5000 generated orders from DESIGN.md (customers and products are drawn first, so their
  random draws are replayed here to keep the stream identical)."
  []
  (let [intn (lcg 42)]
    (doseq [_ (range 1 201)] (when (>= (intn 100) 72) (intn 5)) (intn 60))   ; customers
    (doseq [_ (range 1 51)] (intn 5) (intn 9900))                           ; products
    {:columns ["id" "customer_id" "product_id" "qty" "day"]
     :rows    (vec (for [id (range 1 5001)]
                     (let [r   (intn 100)
                           cid (if (< r 50) (+ 1 (intn 20)) (+ 1 (intn 200)))
                           pid (+ 1 (intn 50))
                           qty (+ 1 (intn 5))
                           day (+ 1 (intn 365))]
                       [id cid pid qty day])))}))

;;; ------------------------------------------------------------------------------------------------
;;; Demo

(defn- format-value [v] (cond (nil? v) "NULL" (double? v) (format "%.2f" v) :else (str v)))

(defn print-table [columns rows]
  (let [cells  (cons (vec columns) (map #(mapv format-value %) rows))
        widths (apply map (fn [& col] (apply max (map count col))) cells)
        line   (fn [r] (str/join " | " (map (fn [w c] (format (str "%-" w "s") c)) widths r)))]
    (println (line (first cells)))
    (println (str/join "-+-" (map #(apply str (repeat % "-")) widths)))
    (doseq [r (rest cells)] (println (line r)))))

(defn- header [s] (println) (println (str "== " s " " (apply str (repeat (max 0 (- 70 (count s))) "=")))))

(def ^:private demo-aggs
  [{:fn "count" :arg :* :name "orders"}
   {:fn "sum" :arg [:col "o.qty"] :name "units"}
   {:fn "avg" :arg [:col "o.qty"] :name "avg_qty"}])

(defn -main [& _]
  (header "GROUP BY customer_id — hash aggregate")
  (println "SELECT customer_id, count(*), sum(qty), avg(qty) FROM orders GROUP BY customer_id")
  (println "Input order: customer 1, 1, 3, 4, 9. One accumulator per group, found by hashing the key.")
  (let [op (hash-aggregate (scan toy-orders "o") [[:col "o.customer_id"]] demo-aggs)]
    (print-table (schema op) (run op)))

  (header "Sort aggregate needs sorted input")
  (let [unsorted {:columns (:columns toy-orders) :rows [[10 1 100 2] [12 3 100 5] [11 1 101 1]]}]
    (println "Feed it customer 1, 3, 1 (unsorted) and customer 1 shows up twice:")
    (let [op (sort-aggregate (scan unsorted "o") [[:col "o.customer_id"]] demo-aggs)]
      (print-table (schema op) (run op)))
    (println)
    (println "Sort first, then it streams: one accumulator alive at a time.")
    (let [op (sort-aggregate (sort-op (scan unsorted "o") [[[:col "o.customer_id"] :asc]])
                             [[:col "o.customer_id"]] demo-aggs)]
      (print-table (schema op) (run op))))

  (header "No GROUP BY: one row, even for empty input")
  (let [empty-t {:columns ["id" "customer_id" "product_id" "qty"] :rows []}
        aggs    [{:fn "count" :arg :* :name "count"} {:fn "sum" :arg [:col "o.qty"] :name "sum"}]]
    (print-table ["count" "sum"] (run (hash-aggregate (scan empty-t "o") [] aggs)))
    (println "count of nothing is 0; sum of nothing is NULL."))

  (let [orders (generate-orders)
        keys   [[[:col "o.qty"] :desc] [[:col "o.day"] :asc]]]
    (header "External merge sort: 5000 orders, memory for 500")
    (let [stats (atom {})
          op    (external-sort (scan orders "o") keys 500 {:stats stats})
          rows  (run op)
          ref   (run (sort-op (scan orders "o") keys))]
      (println (format "  %d runs of ≤500 rows, %d heap pops; merged output = in-memory sort? %s"
                       (:runs @stats) (:heap-pops @stats) (= rows ref)))
      (println "  first 3:")
      (print-table (schema op) (take 3 rows)))

    (header "Top-N: ORDER BY qty DESC, day LIMIT 5")
    (let [full-c (atom 0) top-c (atom 0)
          full   (take 5 (run (sort-op (scan orders "o") keys {:counter full-c})))
          top    (run (top-n (scan orders "o") keys 5 {:counter top-c}))]
      (print-table (:columns orders) top)
      (println (format "  full sort then take 5: %,d comparisons" @full-c))
      (println (format "  top-n heap of 5:       %,d comparisons  (same rows? %s)" @top-c (= (vec full) top))))

    (header "Hash vs sort aggregate on 5000 orders")
    (let [aggs [{:fn "count" :arg :* :name "n"} {:fn "sum" :arg [:col "o.qty"] :name "units"}]
          h    (run (hash-aggregate (scan orders "o") [[:col "o.customer_id"]] aggs))
          s    (run (sort-aggregate (sort-op (scan orders "o") [[[:col "o.customer_id"] :asc]])
                                    [[:col "o.customer_id"]] aggs))]
      (println (format "  hash aggregate: %d groups, first-seen order starts %s" (count h) (pr-str (take 3 h))))
      (println (format "  sort aggregate: %d groups, key order starts       %s" (count s) (pr-str (take 3 s))))
      (println (format "  same groups? %s" (= (set h) (set s)))))))
