;; Generated by lk exercises from clojure/test/lesson04/aggregation_test.clj. DO NOT EDIT;
;; edit the reference lesson and regenerate. Fill in the TODOs here.

(ns exercises.lesson04.aggregation-test
  (:require [clojure.test :refer [deftest is]]
            [exercises.lesson04.aggregation :as a]))

(def aggs [{:fn "count" :arg :* :name "n"} {:fn "sum" :arg [:col "o.qty"] :name "units"}
           {:fn "avg" :arg [:col "o.qty"] :name "avg"} {:fn "min" :arg [:col "o.qty"] :name "lo"}])

(deftest hash-aggregate-first-seen-order
  (is (= [[1 2 3 1.5 1] [3 1 5 5.0 5] [4 1 1 1.0 1] [9 1 3 3.0 3]]
         (a/run (a/hash-aggregate (a/scan a/toy-orders "o") [[:col "o.customer_id"]] aggs)))))

(deftest sort-aggregate-matches-hash
  (let [orders (a/generate-orders)
        h (a/run (a/hash-aggregate (a/scan orders "o") [[:col "o.customer_id"]] aggs))
        s (a/run (a/sort-aggregate (a/sort-op (a/scan orders "o") [[[:col "o.customer_id"] :asc]])
                                   [[:col "o.customer_id"]] aggs))]
    (is (= (set h) (set s)))
    (is (= (sort-by first h) s))))

(deftest empty-input
  (let [empty-t {:columns ["id" "customer_id" "product_id" "qty"] :rows []}]
    (is (= [[0 nil nil nil]] (a/run (a/hash-aggregate (a/scan empty-t "o") [] aggs))))
    (is (= [[0 nil nil nil]] (a/run (a/sort-aggregate (a/scan empty-t "o") [] aggs))))
    (is (= [] (a/run (a/hash-aggregate (a/scan empty-t "o") [[:col "o.qty"]] aggs))))))

(deftest sorting
  (let [orders (a/generate-orders)
        keys [[[:col "o.qty"] :desc] [[:col "o.day"] :asc] [[:col "o.id"] :asc]]
        full (a/run (a/sort-op (a/scan orders "o") keys))]
    (is (= full (a/run (a/external-sort (a/scan orders "o") keys 333))))
    (is (= (take 7 full) (a/run (a/top-n (a/scan orders "o") keys 7))))))

(deftest nulls-last-both-directions
  (let [t {:columns ["v"] :rows [[2] [nil] [1] [3]]}]
    (is (= [[1] [2] [3] [nil]] (a/run (a/sort-op (a/scan t "t") [[[:col "t.v"] :asc]]))))
    (is (= [[3] [2] [1] [nil]] (a/run (a/sort-op (a/scan t "t") [[[:col "t.v"] :desc]]))))))
