// Code generated by lk exercises from go/lesson03/gen.go. DO NOT EDIT;
// edit the reference lesson and regenerate. Fill in the TODOs here.

package lesson03

import "fmt"

// The generated dataset from DESIGN.md, copied into this lesson so it stands alone. A 64-bit LCG,
// bit-identical across the Go and Clojure code, so both produce the same tables.

type lcg struct{ state uint64 }

func (g *lcg) next() uint64 {
	g.state = g.state*6364136223846793005 + 1442695040888963407 // wraps mod 2^64
	return g.state >> 33
}

func (g *lcg) intn(n int) int64 { return int64(g.next() % uint64(n)) }

// Table is a named relation: schema plus rows.
type Table struct {
	Name string
	Cols []string
	Rows []Row
}

// Generate builds customers (200), products (50), orders (5000) from seed 42.
func Generate() (customers, products, orders *Table) {
	g := &lcg{state: 42}
	cities := []string{"Austin", "Boston", "Chicago", "Denver", "Miami", "Oakland", "Portland", "Seattle"}
	categories := []string{"books", "games", "garden", "music", "tools"}

	customers = &Table{Name: "customers", Cols: []string{"customers.id", "customers.name", "customers.city", "customers.age"}}
	for id := int64(1); id <= 200; id++ {
		r := g.intn(100)
		var city string
		switch {
		case r < 40:
			city = cities[0]
		case r < 60:
			city = cities[1]
		case r < 72:
			city = cities[2]
		default:
			city = cities[3+g.intn(5)]
		}
		var age Value = 18 + g.intn(60) // drawn even when it becomes NULL, to keep the stream aligned
		if id%17 == 0 {
			age = nil
		}
		customers.Rows = append(customers.Rows, Row{id, fmt.Sprintf("cust%d", id), city, age})
	}

	products = &Table{Name: "products", Cols: []string{"products.id", "products.name", "products.category", "products.price"}}
	for id := int64(1); id <= 50; id++ {
		category := categories[g.intn(5)]
		price := float64(100+g.intn(9900)) / 100.0
		products.Rows = append(products.Rows, Row{id, fmt.Sprintf("prod%d", id), category, price})
	}

	orders = &Table{Name: "orders", Cols: []string{"orders.id", "orders.customer_id", "orders.product_id", "orders.qty", "orders.day"}}
	for id := int64(1); id <= 5000; id++ {
		var customerID int64
		if g.intn(100) < 50 {
			customerID = 1 + g.intn(20)
		} else {
			customerID = 1 + g.intn(200)
		}
		productID := 1 + g.intn(50)
		qty := 1 + g.intn(5)
		day := 1 + g.intn(365)
		orders.Rows = append(orders.Rows, Row{id, customerID, productID, qty, day})
	}
	return
}
