// Code generated by tools/make_exercises.py from go/lesson07/bytecode.go. DO NOT EDIT;
// edit the reference lesson and regenerate. Fill in the TODOs here.

// Package lesson07 is part 7: compiling a plan to bytecode for a register VM, the way SQLite does.
//
// Lessons 2–6 executed a plan by building a tree of iterator objects. Each operator's state lived
// in its struct fields, but the *control flow* — "which loop am I in, what's next" — lived on the Go
// call stack, spread across nested Next() calls. You can't save a call stack.
//
// Here the plan is compiled into a flat list of instructions (bytecode.go, compiler.go) and run by
// a small virtual machine (vm.go). Now all of the state is plain data: a program counter, an array
// of registers, cursor positions, and the hash tables / sorters / aggregate tables that pipeline
// breakers build. The VM can stop after any instruction (fuel), hand back a row (ResultRow), be
// serialized to JSON (snapshot.go), and be resumed later — in another process, if you like.
package lesson07

import (
	"fmt"
	"strings"
)

// Instr is one instruction: an opcode and up to four operands, SQLite style. P1–P3 are ints
// (registers, cursors, jump targets); P4 is anything else (a table name, a constant, a spec).
type Instr struct {
	Op         string
	P1, P2, P3 int
	P4         any
	Comment    string
	Indent     int // loop nesting, for the listing only
}

// Program is compiled bytecode plus the sizes of the VM state it needs.
type Program struct {
	Instrs  []Instr
	Columns []string // names of the result columns

	NumRegs, NumCursors, NumHashes, NumSorters, NumAggs int
}

// Listing prints the program like SQLite's EXPLAIN.
func (p *Program) Listing() string {
	var b strings.Builder
	fmt.Fprintf(&b, "addr  %-14s %4s %4s %4s  %-18s %s\n", "opcode", "p1", "p2", "p3", "p4", "comment")
	fmt.Fprintf(&b, "----  %-14s %4s %4s %4s  %-18s %s\n", "-------------", "----", "----", "----", "------------------", "-------")
	for addr, in := range p.Instrs {
		p4 := ""
		if in.P4 != nil {
			p4 = fmt.Sprint(in.P4)
			if s, ok := in.P4.(string); ok && in.Op == "Const" {
				p4 = "'" + s + "'"
			}
		}
		if len(p4) > 18 {
			p4 = p4[:17] + "…"
		}
		op := strings.Repeat("  ", in.Indent) + in.Op
		fmt.Fprintf(&b, "%4d  %-14s %4d %4d %4d  %-18s %s\n", addr, op, in.P1, in.P2, in.P3, p4, in.Comment)
	}
	return b.String()
}
