// Code generated by tools/make_exercises.py from go/lesson07/vm.go. DO NOT EDIT;
// edit the reference lesson and regenerate. Fill in the TODOs here.

package lesson07

import (
	"fmt"
	"math"
	"sort"
	"strconv"
	"strings"
)

// Status is why Step returned.
type Status int

const (
	StatusRow       Status = iota // a result row is ready
	StatusDone                    // the program halted
	StatusOutOfFuel               // the fuel budget ran out mid-query; call Step again to continue
)

func (s Status) String() string { return [...]string{"Row", "Done", "OutOfFuel"}[s] }

// State is *everything* a running query is. No pointers into Go stacks, no closures, no open
// iterators — just data. That is what makes Snapshot/Restore possible.
type State struct {
	PC          int
	Halted      bool
	Steps       int // instructions executed so far
	ProgramSize int // sanity check on restore

	Regs    Vals
	Cursors []CursorState
	Hashes  []*HashState
	Sorters []*SorterState
	Aggs    []*AggState
}

// CursorState is a position in a base table. (The data itself isn't state: it's the database.)
type CursorState struct {
	Table string
	Pos   int
}

// HashState is a join hash table plus the probe's position in the current match list.
type HashState struct {
	Buckets  map[string][]Vals
	MatchKey string
	MatchIdx int
}

// SorterState is the rows to sort and the read position once sorted.
type SorterState struct {
	Rows []Vals
	Keys []int
	Desc []bool
	Pos  int
}

// AggState is a hash aggregate: groups in first-seen order, an index by key, and a read position.
type AggState struct {
	Fns       []string // count*, count, sum, min, max, avg
	NKeys     int
	Groups    []*Group
	Index     map[string]int
	Pos       int
	Finalized bool
}

type Group struct {
	Key  Vals
	Accs []Acc
}

// Acc accumulates one aggregate.
type Acc struct {
	Count     int64
	Sum, Best Value
}

// VM runs a Program against a database.
type VM struct {
	prog *Program
	db   DB
	S    State

	// Trace, if set, is called before each instruction executes.
	Trace func(pc int, in Instr, regs Vals)
}

func NewVM(prog *Program, db DB) *VM {
	vm := &VM{prog: prog, db: db}
	vm.S = State{
		ProgramSize: len(prog.Instrs),
		Regs:        make(Vals, prog.NumRegs),
		Cursors:     make([]CursorState, prog.NumCursors),
		Hashes:      make([]*HashState, prog.NumHashes),
		Sorters:     make([]*SorterState, prog.NumSorters),
		Aggs:        make([]*AggState, prog.NumAggs),
	}
	return vm
}

// Step runs until a row is produced, the program halts, or `fuel` instructions have executed.
// Everything it needs to continue lives in vm.S, so returning — for any reason — loses nothing.
func (vm *VM) Step(fuel int) (Row, Status) {
	// EXERCISE(vm-step-loop): Fetch–execute until fuel runs out: advance PC before executing (jumps overwrite it). Halt ends the program; ResultRow returns a copy of its registers as a row (PC already points past it, so the next Step resumes there); everything else goes to exec.
	panic("TODO: exercise vm-step-loop")
}

// cursorOp executes the instructions that move through a base table: a cursor is just a table
// name and a row position.
func (vm *VM) cursorOp(in Instr) {
	// EXERCISE(vm-cursor-ops): OpenScan points a cursor at a table; Rewind moves it to row 0 (or jumps to P2 if the table is empty); Column copies column P2 of the current row into register P3; Next advances and jumps back to P2 while rows remain.
	panic("TODO: exercise vm-cursor-ops")
}

// exec executes every other instruction.
func (vm *VM) exec(in Instr) {
	s := &vm.S
	r := s.Regs
	switch in.Op {
	case "Init", "Goto":
		s.PC = in.P2
	case "OpenScan", "Rewind", "Column", "Next":
		vm.cursorOp(in)

	// --- registers and expressions
	case "Const":
		r[in.P2] = in.P4
	case "Copy":
		r[in.P2] = r[in.P1]
	case "Add", "Sub", "Mul", "Div", "Eq", "Ne", "Lt", "Le", "Gt", "Ge":
		r[in.P3] = apply(in.Op, r[in.P1], r[in.P2])
	case "And":
		r[in.P3] = and3(r[in.P1], r[in.P2])
	case "Or":
		r[in.P3] = or3(r[in.P1], r[in.P2])
	case "Not":
		if v := r[in.P1]; v != nil {
			r[in.P3] = !v.(bool)
		} else {
			r[in.P3] = nil
		}
	case "IsNull":
		r[in.P3] = r[in.P1] == nil
	case "NotNull":
		r[in.P3] = r[in.P1] != nil
	case "Func":
		r[in.P3] = callFunc(in.P4.(string), r[in.P1:in.P1+in.P2])

	// --- control flow
	case "IfNot":
		if r[in.P1] != true {
			s.PC = in.P2
		}
	case "If":
		if r[in.P1] == true {
			s.PC = in.P2
		}
	case "DecrJumpZero":
		n := r[in.P1].(int64) - 1
		r[in.P1] = n
		if n <= 0 {
			s.PC = in.P2
		}

	// --- hash join
	case "HashOpen":
		s.Hashes[in.P1] = &HashState{Buckets: map[string][]Vals{}}
	case "HashInsert":
		if k := r[in.P2]; k != nil { // NULL keys never match: don't store them
			h := s.Hashes[in.P1]
			ks := keyString([]Value{k})
			h.Buckets[ks] = append(h.Buckets[ks], append(Vals{}, r[in.P3:in.P3+in.P4.(int)]...))
		}
	case "HashSeek":
		h := s.Hashes[in.P1]
		k := r[in.P2]
		if k == nil || len(h.Buckets[keyString([]Value{k})]) == 0 {
			s.PC = in.P3
		} else {
			h.MatchKey, h.MatchIdx = keyString([]Value{k}), 0
		}
	case "HashColumn":
		h := s.Hashes[in.P1]
		r[in.P3] = h.Buckets[h.MatchKey][h.MatchIdx][in.P2]
	case "HashNext":
		h := s.Hashes[in.P1]
		h.MatchIdx++
		if h.MatchIdx < len(h.Buckets[h.MatchKey]) {
			s.PC = in.P2
		}

	// --- sorter
	case "SorterOpen":
		st := &SorterState{}
		for _, part := range strings.Split(in.P4.(string), ",") {
			f := strings.Fields(part)
			col, _ := strconv.Atoi(f[0])
			st.Keys = append(st.Keys, col)
			st.Desc = append(st.Desc, len(f) > 1 && f[1] == "desc")
		}
		s.Sorters[in.P1] = st
	case "SorterInsert":
		st := s.Sorters[in.P1]
		st.Rows = append(st.Rows, append(Vals{}, r[in.P2:in.P2+in.P3]...))
	case "SorterSort":
		st := s.Sorters[in.P1]
		sort.SliceStable(st.Rows, func(i, j int) bool { return st.less(st.Rows[i], st.Rows[j]) })
		st.Pos = 0
		if len(st.Rows) == 0 {
			s.PC = in.P2
		}
	case "SorterColumn":
		st := s.Sorters[in.P1]
		r[in.P3] = st.Rows[st.Pos][in.P2]
	case "SorterNext":
		st := s.Sorters[in.P1]
		st.Pos++
		if st.Pos < len(st.Rows) {
			s.PC = in.P2
		}

	// --- aggregation
	case "AggOpen":
		s.Aggs[in.P1] = &AggState{Fns: strings.Split(in.P4.(string), ","), NKeys: in.P2, Index: map[string]int{}}
	case "AggStep":
		a := s.Aggs[in.P1]
		key := r[in.P2 : in.P2+in.P3]
		ks := keyString(key)
		gi, ok := a.Index[ks]
		if !ok {
			gi = len(a.Groups)
			a.Index[ks] = gi
			a.Groups = append(a.Groups, &Group{Key: append(Vals{}, key...), Accs: make([]Acc, len(a.Fns))})
		}
		vals := in.P4.(int)
		for i, fn := range a.Fns {
			a.Groups[gi].Accs[i].step(fn, r[vals+i])
		}
	case "AggRewind":
		a := s.Aggs[in.P1]
		if len(a.Groups) == 0 && a.NKeys == 0 { // no GROUP BY: one row even for empty input
			a.Groups = append(a.Groups, &Group{Accs: make([]Acc, len(a.Fns))})
		}
		a.Pos, a.Finalized = 0, true
		if len(a.Groups) == 0 {
			s.PC = in.P2
		}
	case "AggColumn":
		a := s.Aggs[in.P1]
		g := a.Groups[a.Pos]
		if in.P2 < a.NKeys {
			r[in.P3] = g.Key[in.P2]
		} else {
			i := in.P2 - a.NKeys
			r[in.P3] = g.Accs[i].result(a.Fns[i])
		}
	case "AggNext":
		a := s.Aggs[in.P1]
		a.Pos++
		if a.Pos < len(a.Groups) {
			s.PC = in.P2
		}

	default:
		panic("unknown opcode " + in.Op)
	}
}

// Run executes to completion and returns every row.
func (vm *VM) Run() []Row {
	var out []Row
	for {
		row, st := vm.Step(math.MaxInt)
		if st == StatusDone {
			return out
		}
		out = append(out, row)
	}
}

// ---------------------------------------------------------------------------------------------
// Helpers: values, 3VL, aggregates, sorting
// ---------------------------------------------------------------------------------------------

func apply(op string, a, b Value) Value {
	if a == nil || b == nil {
		return nil
	}
	switch op {
	case "Add", "Sub", "Mul", "Div":
		ai, aInt := a.(int64)
		bi, bInt := b.(int64)
		if aInt && bInt && op != "Div" {
			switch op {
			case "Add":
				return ai + bi
			case "Sub":
				return ai - bi
			default:
				return ai * bi
			}
		}
		x, y := toFloat(a), toFloat(b)
		switch op {
		case "Add":
			return x + y
		case "Sub":
			return x - y
		case "Mul":
			return x * y
		}
		if y == 0 {
			return nil
		}
		return x / y
	}
	c := Compare(a, b)
	switch op {
	case "Eq":
		return c == 0
	case "Ne":
		return c != 0
	case "Lt":
		return c < 0
	case "Le":
		return c <= 0
	case "Gt":
		return c > 0
	default:
		return c >= 0
	}
}

func and3(a, b Value) Value {
	if a == false || b == false {
		return false
	}
	if a == nil || b == nil {
		return nil
	}
	return true
}

func or3(a, b Value) Value {
	if a == true || b == true {
		return true
	}
	if a == nil || b == nil {
		return nil
	}
	return false
}

func callFunc(name string, args Vals) Value {
	if name == "coalesce" {
		for _, a := range args {
			if a != nil {
				return a
			}
		}
		return nil
	}
	if args[0] == nil {
		return nil
	}
	switch name {
	case "lower":
		return strings.ToLower(args[0].(string))
	case "upper":
		return strings.ToUpper(args[0].(string))
	case "length":
		return int64(len(args[0].(string)))
	case "abs":
		if i, ok := args[0].(int64); ok {
			if i < 0 {
				return -i
			}
			return i
		}
		return math.Abs(args[0].(float64))
	}
	panic("unknown function " + name)
}

func (a *Acc) step(fn string, v Value) {
	if fn == "count*" {
		a.Count++
		return
	}
	if v == nil {
		return
	}
	a.Count++
	switch fn {
	case "sum", "avg":
		if a.Sum == nil {
			a.Sum = v
		} else if x, ok := a.Sum.(int64); ok {
			if y, ok := v.(int64); ok {
				a.Sum = x + y
				break
			}
			a.Sum = float64(x) + toFloat(v)
		} else {
			a.Sum = toFloat(a.Sum) + toFloat(v)
		}
	case "min":
		if a.Best == nil || Compare(v, a.Best) < 0 {
			a.Best = v
		}
	case "max":
		if a.Best == nil || Compare(v, a.Best) > 0 {
			a.Best = v
		}
	}
}

func (a *Acc) result(fn string) Value {
	switch fn {
	case "count", "count*":
		return a.Count
	case "sum":
		return a.Sum
	case "avg":
		if a.Count == 0 {
			return nil
		}
		return toFloat(a.Sum) / float64(a.Count)
	}
	return a.Best
}

// less orders sorter records by their key columns; NULLs last in both directions.
func (st *SorterState) less(a, b Vals) bool {
	for i, k := range st.Keys {
		x, y := a[k], b[k]
		switch {
		case x == nil && y == nil:
			continue
		case x == nil:
			return false
		case y == nil:
			return true
		}
		c := Compare(x, y)
		if st.Desc[i] {
			c = -c
		}
		if c != 0 {
			return c < 0
		}
	}
	return false
}

// String renders the VM's position for demos.
func (vm *VM) String() string {
	return fmt.Sprintf("pc=%d steps=%d halted=%v", vm.S.PC, vm.S.Steps, vm.S.Halted)
}
