;; Generated by lk exercises from clojure/test/lesson01/expressions_test.clj. DO NOT EDIT;
;; edit the reference lesson and regenerate. Fill in the TODOs here.

(ns exercises.lesson01.expressions-test
  (:require [clojure.test :refer [deftest is are testing]]
            [exercises.lesson01.expressions :as e]))

(def schema e/customers-schema)
(def bo (nth e/customers 1))
(def ada (first e/customers))

(deftest three-valued-logic
  (are [a b and-r or-r] (and (= and-r (e/and3 a b)) (= or-r (e/or3 a b)))
    true  nil   nil   true
    false nil   false nil
    nil   nil   nil   nil
    true  false false true)
  (is (nil? (e/not3 nil))))

(deftest arithmetic-semantics
  (is (= 5 (e/arith :+ 2 3)))
  (is (= 3.5 (e/arith :/ 7 2)))
  (is (double? (e/arith :/ 4 2)))
  (is (nil? (e/arith :/ 1 0)))
  (is (nil? (e/arith :+ nil 1)))
  (is (= 3.0 (e/arith :* 2 1.5))))

(deftest comparisons
  (is (nil? (e/comparison :> nil 30)))
  (is (true? (e/comparison := 1 1.0)))
  (is (true? (e/comparison :< "Ada" "Bo")))
  (is (thrown? clojure.lang.ExceptionInfo (e/comparison :< 1 "a"))))

(deftest tree-walk-and-compiled-agree
  (let [exprs [[:and [:> [:col "age"] [:lit 30]] [:= [:col "city"] [:lit "Austin"]]]
               [:or [:> [:col "age"] [:lit 30]] [:= [:col "city"] [:lit "Boston"]]]
               [:fn "coalesce" [:col "age"] [:lit 0]]
               [:is-null [:col "customers.age"]]
               [:+ [:col "id"] [:lit 1.5]]
               [:= [:fn "lower" [:col "name"]] [:lit "bo"]]
               [:not [:< [:col "age"] [:lit 40]]]]]
    (doseq [x exprs row e/customers]
      (is (= (e/eval-expr x schema row) ((e/compile-expr x schema) row)) (pr-str x row)))))

(deftest null-handling
  (testing "NULL > 30 is NULL; NULL AND false is false"
    (is (nil? (e/eval-expr [:> [:col "age"] [:lit 30]] schema bo)))
    (is (false? (e/eval-expr [:and [:> [:col "age"] [:lit 30]] [:= [:col "city"] [:lit "Austin"]]] schema bo))))
  (is (= 0 (e/eval-expr [:fn "coalesce" [:col "age"] [:lit 0]] schema bo)))
  (is (= 36 (e/eval-expr [:fn "coalesce" [:col "age"] [:lit 0]] schema ada))))

(deftest column-resolution
  (is (= 3 (e/col-index schema "age")))
  (is (= 3 (e/col-index schema "customers.age")))
  (is (thrown? clojure.lang.ExceptionInfo (e/col-index schema "nope")))
  (is (thrown? clojure.lang.ExceptionInfo (e/col-index ["a.x" "b.x"] "x"))))
