;; Generated by tools/make_exercises.py from clojure/test/lesson03/joins_test.clj. DO NOT EDIT;
;; edit the reference lesson and regenerate. Fill in the TODOs here.

(ns exercises.lesson03.joins-test
  (:require [clojure.test :refer [deftest is]]
            [exercises.lesson03.joins :as j]))

(def c #(j/scan (get-in j/toy [:customers]) "c"))
(def o #(j/scan (get-in j/toy [:orders]) "o"))
(def on [:= [:col "c.id"] [:col "o.customer_id"]])

(deftest three-algorithms-agree
  (let [nl (j/run (j/nl-join (c) (o) on {}))
        h  (j/run (j/hash-join (c) (o) [:col "c.id"] [:col "o.customer_id"] {}))
        m  (j/run (j/merge-join (j/sort-op (c) [:col "c.id"]) (j/sort-op (o) [:col "o.customer_id"])
                                [:col "c.id"] [:col "o.customer_id"] {}))]
    (is (= 4 (count nl)))
    (is (= nl h))
    (is (= (set nl) (set m)))))

(deftest left-outer
  (let [rows (j/run (j/hash-join (c) (o) [:col "c.id"] [:col "o.customer_id"] {:kind :left}))]
    (is (= 5 (count rows)))
    (is (some #(= [2 "Bo" "Boston" nil nil nil nil nil] %) rows)))
  (let [rows (j/run (j/nl-join (o) (c) on {:kind :left}))]
    (is (some #(= [14 9 101 3 nil nil nil nil] %) rows))))

(deftest counters
  (let [k (atom {:comparisons 0})]
    (j/run (j/nl-join (c) (o) on {:counters k}))
    (is (= 20 (:comparisons @k)))))

(deftest generated-data-is-deterministic
  (let [{:keys [customers orders products]} (j/generate)]
    (is (= 200 (count (:rows customers))))
    (is (= 50 (count (:rows products))))
    (is (= 5000 (count (:rows orders))))
    (is (= (j/generate) (j/generate)))
    (let [k1 (atom {:comparisons 0}) k2 (atom {:comparisons 0})
          a (j/run (j/hash-join (j/scan customers "c") (j/scan orders "o") [:col "c.id"] [:col "o.customer_id"] {:counters k1}))
          b (j/run (j/merge-join (j/sort-op (j/scan customers "c") [:col "c.id"]) (j/sort-op (j/scan orders "o") [:col "o.customer_id"])
                                 [:col "c.id"] [:col "o.customer_id"] {:counters k2}))]
      (is (= 5000 (count a)))
      (is (= (set a) (set b))))))
