// Code generated by tools/make_exercises.py from go/lesson06/exec.go. DO NOT EDIT;
// edit the reference lesson and regenerate. Fill in the TODOs here.

package lesson06

// Compact operators copied from lessons 2, 3 and 5, so the planner's plans can actually run and
// we can compare estimated row counts with real ones.

import "sort"

type Operator interface {
	Open()
	Next() (Row, bool)
	Close()
	Schema() []string
}

// Index is a stand-in for lesson 5's B+tree: (key, row id) pairs sorted by key, searched by binary
// search. The planner only needs to know that it exists and what a lookup roughly costs.
type Index struct {
	Col     string
	entries []indexEntry
}

type indexEntry struct {
	key Value
	id  int
}

func BuildIndex(t *Table, col string) *Index {
	ci := indexOf(t.Cols, col)
	idx := &Index{Col: col}
	for id, r := range t.Rows {
		if r[ci] != nil {
			idx.entries = append(idx.entries, indexEntry{r[ci], id})
		}
	}
	sort.SliceStable(idx.entries, func(i, j int) bool { return Compare(idx.entries[i].key, idx.entries[j].key) < 0 })
	return idx
}

// Lookup returns row ids with key op v, in key order (ties in row-id order).
func (x *Index) Lookup(op string, v Value) []int {
	n := len(x.entries)
	first := sort.Search(n, func(i int) bool { return Compare(x.entries[i].key, v) >= 0 }) // first ≥ v
	after := sort.Search(n, func(i int) bool { return Compare(x.entries[i].key, v) > 0 })  // first > v
	lo, hi := 0, n
	switch op {
	case "=":
		lo, hi = first, after
	case "<":
		hi = first
	case "<=":
		hi = after
	case ">":
		lo = after
	case ">=":
		lo = first
	default:
		panic("index can't answer " + op)
	}
	ids := make([]int, 0, hi-lo)
	for _, e := range x.entries[lo:hi] {
		ids = append(ids, e.id)
	}
	return ids
}

func concat(l, r Row) Row { return append(append(make(Row, 0, len(l)+len(r)), l...), r...) }

func and(preds []Expr) Expr {
	e := preds[0]
	for _, p := range preds[1:] {
		e = B("and", e, p)
	}
	return e
}

// ---------------------------------------------------------------------------------------------

type Scan struct {
	T   *Table
	pos int
}

func (s *Scan) Open()            { s.pos = 0 }
func (s *Scan) Close()           {}
func (s *Scan) Schema() []string { return s.T.Cols }
func (s *Scan) Next() (Row, bool) {
	if s.pos >= len(s.T.Rows) {
		return nil, false
	}
	s.pos++
	return s.T.Rows[s.pos-1], true
}

type IndexScan struct {
	T     *Table
	Index *Index
	Op    string
	V     Value
	ids   []int
}

func (s *IndexScan) Open()            { s.ids = s.Index.Lookup(s.Op, s.V) }
func (s *IndexScan) Close()           {}
func (s *IndexScan) Schema() []string { return s.T.Cols }
func (s *IndexScan) Next() (Row, bool) {
	if len(s.ids) == 0 {
		return nil, false
	}
	id := s.ids[0]
	s.ids = s.ids[1:]
	return s.T.Rows[id], true
}

type Filter struct {
	Child Operator
	Pred  func(Row) Value
}

func (f *Filter) Open()            { f.Child.Open() }
func (f *Filter) Close()           { f.Child.Close() }
func (f *Filter) Schema() []string { return f.Child.Schema() }
func (f *Filter) Next() (Row, bool) {
	for {
		r, ok := f.Child.Next()
		if !ok {
			return nil, false
		}
		if f.Pred(r) == true {
			return r, true
		}
	}
}

// HashJoin builds on Right, probes with Left.
type HashJoin struct {
	Left, Right       Operator
	LeftKey, RightKey int
	table             map[Value][]Row
	cur               Row
	matches           []Row
}

func (j *HashJoin) Schema() []string {
	return append(append([]string{}, j.Left.Schema()...), j.Right.Schema()...)
}
func (j *HashJoin) Close() { j.Left.Close() }
func (j *HashJoin) Open() {
	j.table = map[Value][]Row{}
	j.Right.Open()
	for {
		r, ok := j.Right.Next()
		if !ok {
			break
		}
		if k := r[j.RightKey]; k != nil { // generated join keys are all int64, so Go map keys work
			j.table[k] = append(j.table[k], r)
		}
	}
	j.Right.Close()
	j.Left.Open()
	j.matches = nil
}
func (j *HashJoin) Next() (Row, bool) {
	for len(j.matches) == 0 {
		l, ok := j.Left.Next()
		if !ok {
			return nil, false
		}
		j.cur = l
		if k := l[j.LeftKey]; k != nil {
			j.matches = j.table[k]
		}
	}
	m := j.matches[0]
	j.matches = j.matches[1:]
	return concat(j.cur, m), true
}

// NLJoin rewinds Right for every Left row.
type NLJoin struct {
	Left, Right Operator
	Pred        func(Row) Value // nil = cross product
	cur         Row
}

func (j *NLJoin) Schema() []string {
	return append(append([]string{}, j.Left.Schema()...), j.Right.Schema()...)
}
func (j *NLJoin) Open()  { j.Left.Open(); j.cur = nil }
func (j *NLJoin) Close() { j.Left.Close() }
func (j *NLJoin) Next() (Row, bool) {
	for {
		if j.cur == nil {
			l, ok := j.Left.Next()
			if !ok {
				return nil, false
			}
			j.cur = l
			j.Right.Close()
			j.Right.Open()
		}
		r, ok := j.Right.Next()
		if !ok {
			j.cur = nil
			continue
		}
		row := concat(j.cur, r)
		if j.Pred == nil || j.Pred(row) == true {
			return row, true
		}
	}
}

// IndexNLJoin looks each outer row's key up in the inner table's index, then applies the inner
// table's own filters to what it fetched.
type IndexNLJoin struct {
	Outer       Operator
	OuterKey    int
	Inner       *Table
	Index       *Index
	InnerFilter func(Row) Value // nil = none
	cur         Row
	ids         []int
}

func (j *IndexNLJoin) Schema() []string {
	return append(append([]string{}, j.Outer.Schema()...), j.Inner.Cols...)
}
func (j *IndexNLJoin) Open()  { j.Outer.Open(); j.ids = nil }
func (j *IndexNLJoin) Close() { j.Outer.Close() }
func (j *IndexNLJoin) Next() (Row, bool) {
	for {
		for len(j.ids) == 0 {
			l, ok := j.Outer.Next()
			if !ok {
				return nil, false
			}
			j.cur = l
			if k := l[j.OuterKey]; k != nil {
				j.ids = j.Index.Lookup("=", k)
			}
		}
		r := j.Inner.Rows[j.ids[0]]
		j.ids = j.ids[1:]
		if j.InnerFilter == nil || j.InnerFilter(r) == true {
			return concat(j.cur, r), true
		}
	}
}

// counting wraps an operator to record how many rows it really produced, for EXPLAIN ANALYZE.
// An NL join's inner side is opened once per outer row, so rows accumulate across Loops.
type counting struct {
	Operator
	plan *Plan
}

func (c *counting) Open() { c.plan.Loops++; c.Operator.Open() }
func (c *counting) Next() (Row, bool) {
	r, ok := c.Operator.Next()
	if ok {
		c.plan.ActualRows++
	}
	return r, ok
}
