// Code generated by tools/make_exercises.py from go/lesson06/expr.go. DO NOT EDIT;
// edit the reference lesson and regenerate. Fill in the TODOs here.

package lesson06

// Copied (compact) from lesson 1 so this lesson stands alone: values, the expression tree, and
// closure compilation. The planner needs the *tree* (to estimate selectivity from its shape); the
// executor needs the *closure*.

import (
	"fmt"
	"strings"
)

type Value = any
type Row = []Value

type Expr interface{ String() string }

type Col struct{ Name string } // qualified: "orders.qty"
type Lit struct{ V Value }
type Bin struct {
	Op   string // + - * / = != < <= > >= and or
	L, R Expr
}
type Not struct{ E Expr }
type IsNull struct {
	E      Expr
	Negate bool
}

func C(name string) Expr { return Col{Name: name} }
func L(v Value) Expr {
	if i, ok := v.(int); ok {
		v = int64(i)
	}
	return Lit{V: v}
}
func B(op string, l, r Expr) Expr { return Bin{Op: op, L: l, R: r} }

func (c Col) String() string { return c.Name }
func (l Lit) String() string {
	if s, ok := l.V.(string); ok {
		return "'" + s + "'"
	}
	return Format(l.V)
}
func (b Bin) String() string { return b.L.String() + " " + strings.ToUpper(b.Op) + " " + b.R.String() }
func (n Not) String() string { return "NOT (" + n.E.String() + ")" }
func (n IsNull) String() string {
	if n.Negate {
		return n.E.String() + " IS NOT NULL"
	}
	return n.E.String() + " IS NULL"
}

func Format(v Value) string {
	switch v := v.(type) {
	case nil:
		return "NULL"
	case float64:
		return fmt.Sprintf("%.2f", v)
	}
	return fmt.Sprint(v)
}

// Columns lists every column an expression mentions.
func Columns(e Expr) []string {
	switch e := e.(type) {
	case Col:
		return []string{e.Name}
	case Bin:
		return append(Columns(e.L), Columns(e.R)...)
	case Not:
		return Columns(e.E)
	case IsNull:
		return Columns(e.E)
	}
	return nil
}

func indexOf(schema []string, name string) int {
	for i, c := range schema {
		if c == name {
			return i
		}
	}
	panic("unknown column " + name)
}

// Compile turns an expression into a function of a row with the given schema.
func Compile(e Expr, schema []string) func(Row) Value {
	switch e := e.(type) {
	case Col:
		i := indexOf(schema, e.Name)
		return func(r Row) Value { return r[i] }
	case Lit:
		return func(Row) Value { return e.V }
	case Not:
		f := Compile(e.E, schema)
		return func(r Row) Value {
			if v := f(r); v != nil {
				return !v.(bool)
			}
			return nil
		}
	case IsNull:
		f := Compile(e.E, schema)
		return func(r Row) Value { return (f(r) == nil) != e.Negate }
	case Bin:
		l, r := Compile(e.L, schema), Compile(e.R, schema)
		switch e.Op {
		case "and":
			return func(row Row) Value {
				a, b := l(row), r(row)
				if a == false || b == false {
					return false
				}
				if a == nil || b == nil {
					return nil
				}
				return true
			}
		case "or":
			return func(row Row) Value {
				a, b := l(row), r(row)
				if a == true || b == true {
					return true
				}
				if a == nil || b == nil {
					return nil
				}
				return false
			}
		}
		op := e.Op
		return func(row Row) Value { return apply(op, l(row), r(row)) }
	}
	panic(fmt.Sprintf("unknown expression %T", e))
}

func apply(op string, a, b Value) Value {
	if a == nil || b == nil {
		return nil
	}
	switch op {
	case "+", "-", "*", "/":
		ai, aInt := a.(int64)
		bi, bInt := b.(int64)
		if aInt && bInt && op != "/" {
			switch op {
			case "+":
				return ai + bi
			case "-":
				return ai - bi
			default:
				return ai * bi
			}
		}
		x, y := toFloat(a), toFloat(b)
		switch op {
		case "+":
			return x + y
		case "-":
			return x - y
		case "*":
			return x * y
		}
		if y == 0 {
			return nil
		}
		return x / y
	}
	c := Compare(a, b)
	switch op {
	case "=":
		return c == 0
	case "!=":
		return c != 0
	case "<":
		return c < 0
	case "<=":
		return c <= 0
	case ">":
		return c > 0
	case ">=":
		return c >= 0
	}
	panic("unknown operator " + op)
}

func Compare(a, b Value) int {
	switch x := a.(type) {
	case int64:
		if y, ok := b.(int64); ok {
			return cmp3(x < y, x > y)
		}
		return cmpF(float64(x), toFloat(b))
	case float64:
		return cmpF(x, toFloat(b))
	case string:
		y := b.(string)
		return cmp3(x < y, x > y)
	case bool:
		y := b.(bool)
		return cmp3(!x && y, x && !y)
	}
	panic(fmt.Sprintf("cannot compare %v and %v", a, b))
}

func toFloat(v Value) float64 {
	if i, ok := v.(int64); ok {
		return float64(i)
	}
	return v.(float64)
}
func cmpF(a, b float64) int { return cmp3(a < b, a > b) }
func cmp3(less, greater bool) int {
	if less {
		return -1
	}
	if greater {
		return 1
	}
	return 0
}
