// Code generated by tools/make_exercises.py from go/lesson06/planner_test.go. DO NOT EDIT;
// edit the reference lesson and regenerate. Fill in the TODOs here.

package lesson06

import (
	"math"
	"testing"
)

func TestAnalyze(t *testing.T) {
	cat := NewCatalog()
	age := cat.Stats["customers"].Cols["customers.age"]
	if age.Nulls != 11 || age.Rows != 200 { // ids divisible by 17: 17, 34, …, 187
		t.Fatalf("age stats: %+v", age)
	}
	total := 0
	for _, b := range age.Hist {
		total += b.Count
	}
	if total != age.Rows-age.Nulls {
		t.Fatalf("histogram covers %d of %d non-null rows", total, age.Rows-age.Nulls)
	}
	if ndv := cat.Stats["customers"].Cols["customers.city"].NDV; ndv != 8 {
		t.Fatalf("city ndv = %d", ndv)
	}
}

func TestRangeSelectivityUsesHistogram(t *testing.T) {
	cat := NewCatalog()
	// The skew: half of orders go to customers 1..20. A min/max-only estimate would say ~10%.
	p := B("<=", C("orders.customer_id"), L(20))
	est := cat.Selectivity(p) * 5000
	actual := 0
	for _, r := range cat.Tables["orders"].Rows {
		if r[1].(int64) <= 20 {
			actual++
		}
	}
	if math.Abs(est-float64(actual))/float64(actual) > 0.15 {
		t.Fatalf("estimate %0.f vs actual %d", est, actual)
	}
}

// bruteForce counts rows of the three-way query with nested loops and no planner.
func bruteForce(cat *Catalog) int {
	n := 0
	for _, o := range cat.Tables["orders"].Rows {
		for _, c := range cat.Tables["customers"].Rows {
			if o[1] != c[0] || c[2] != "Seattle" || o[3].(int64) < 4 {
				continue
			}
			for _, p := range cat.Tables["products"].Rows {
				if o[2] == p[0] && p[2] == "games" {
					n++
				}
			}
		}
	}
	return n
}

func TestPlanReturnsCorrectRows(t *testing.T) {
	cat := NewCatalog()
	q := Query{Tables: []string{"orders", "customers", "products"}, Where: []Expr{
		B("=", C("orders.customer_id"), C("customers.id")),
		B("=", C("orders.product_id"), C("products.id")),
		B("=", C("customers.city"), L("Seattle")),
		B("=", C("products.category"), L("games")),
		B(">=", C("orders.qty"), L(4)),
	}}
	_, plan := cat.Plan(q)
	if got, want := len(Run(plan)), bruteForce(cat); got != want {
		t.Fatalf("plan returned %d rows, brute force %d\n%s", got, want, Explain(plan, true))
	}
	// Every join order must give the same answer: try the query with tables listed differently.
	q.Tables = []string{"products", "customers", "orders"}
	_, plan = cat.Plan(q)
	if got, want := len(Run(plan)), bruteForce(cat); got != want {
		t.Fatalf("reordered: %d vs %d", got, want)
	}
}

func TestPointLookupUsesIndex(t *testing.T) {
	cat := NewCatalog()
	_, plan := cat.Plan(Query{Tables: []string{"orders"}, Where: []Expr{B("=", C("orders.customer_id"), L(7))}})
	if plan.Op != "IndexScan" {
		t.Fatalf("expected IndexScan, got\n%s", Explain(plan, false))
	}
	_, plan = cat.Plan(Query{Tables: []string{"orders"}, Where: []Expr{B("<", C("orders.qty"), L(5))}})
	if plan.Op == "IndexScan" {
		t.Fatal("qty has no index")
	}
}

func TestEqSelectivityAssumesUniformity(t *testing.T) {
	cat := NewCatalog()
	// 8 cities, no NULLs: every city is guessed at 1/8 of 200 customers, whatever the truth.
	if est := cat.Selectivity(B("=", C("customers.city"), L("Austin"))) * 200; math.Abs(est-25) > 1e-9 {
		t.Fatalf("city = 'Austin' estimated %.2f rows, want 25", est)
	}
	// NULLs never match: age has 11 NULLs out of 200 and 54 distinct values.
	want := (189.0 / 200.0) / 54.0
	if got := cat.Selectivity(B("=", C("customers.age"), L(40))); math.Abs(got-want) > 1e-9 {
		t.Fatalf("age = 40 selectivity %v, want %v", got, want)
	}
	// != is the complement among non-NULL rows.
	if got := cat.Selectivity(B("!=", C("customers.age"), L(40))); math.Abs(got-(189.0/200.0-want)) > 1e-9 {
		t.Fatalf("age != 40 selectivity %v", got)
	}
}

func TestJoinCardinality(t *testing.T) {
	cat := NewCatalog()
	// |customers|·|orders| / max(ndv(customers.id)=200, ndv(orders.customer_id)=200) = 5000
	est := cat.Selectivity(B("=", C("orders.customer_id"), C("customers.id"))) * 200 * 5000
	if math.Abs(est-5000) > 1e-6 {
		t.Fatalf("join estimate %.1f, want 5000", est)
	}
	// products.id has 50 distinct values, orders.product_id 50: 50·5000/50 = 5000 again.
	est = cat.Selectivity(B("=", C("orders.product_id"), C("products.id"))) * 50 * 5000
	if math.Abs(est-5000) > 1e-6 {
		t.Fatalf("product join estimate %.1f, want 5000", est)
	}
}
