// Code generated by lk exercises. DO NOT EDIT.

package lesson06

import (
	"fmt"
	"strings"
	"testing"
)

// lkTodoGuard runs deferred at the top of every test (and subtest). In Go a panic in one test
// kills the whole test binary, so an unfinished exercise (a TODO panic) would hide every other
// result. The guard turns any panic into an ordinary failure of that test, and the run goes on.
func lkTodoGuard(t *testing.T) {
	if r := recover(); r != nil {
		if msg := fmt.Sprint(r); strings.HasPrefix(msg, "TODO: exercise ") {
			t.Errorf("not implemented yet: %s", strings.TrimPrefix(msg, "TODO: "))
		} else {
			t.Errorf("panic: %v", r)
		}
	}
}
