// Code generated by lk exercises from go/lesson04/aggregation.go. DO NOT EDIT;
// edit the reference lesson and regenerate. Fill in the TODOs here.

// Package lesson04 is part 4: aggregation and sorting — the operators that can't stream.
//
// A Filter can emit a row the moment it sees it. GROUP BY can't: the last input row might belong
// to the first group. ORDER BY can't either: the last input row might sort first. These are
// "pipeline breakers". There are two ways to group, and they trade memory for an ordering
// requirement:
//
//   - HashAggregate keeps one accumulator per group in a hash table. Any input order; memory grows
//     with the number of groups.
//   - SortAggregate needs input sorted on the group key, then needs memory for only one group at a
//     time and can emit each group as soon as the key changes.
//
// Sorting itself: Sort (all in memory), ExternalSort (sorted runs + k-way merge, the way you sort
// more data than fits in memory), and TopN (ORDER BY … LIMIT n with a size-n heap).
package lesson04

import (
	"container/heap"
	"sort"
)

// ---------------------------------------------------------------------------------------------
// Aggregate functions
// ---------------------------------------------------------------------------------------------

// AggSpec is one aggregate: Fn ∈ count, sum, min, max, avg. Col = -1 means count(*).
type AggSpec struct {
	Fn  string
	Col int
}

// acc accumulates one aggregate for one group.
type acc struct {
	fn    string
	count int64 // non-NULL inputs seen (or all rows, for count(*))
	sum   Value // int64 while all inputs are ints, float64 after the first float
	best  Value // min / max so far
}

func (a *acc) step(v Value, star bool) {
	if star {
		a.count++
		return
	}
	if v == nil {
		return // aggregates skip NULLs
	}
	a.count++
	switch a.fn {
	case "sum", "avg":
		a.sum = add(a.sum, v)
	case "min":
		if a.best == nil || Compare(v, a.best) < 0 {
			a.best = v
		}
	case "max":
		if a.best == nil || Compare(v, a.best) > 0 {
			a.best = v
		}
	}
}

func (a *acc) result() Value {
	switch a.fn {
	case "count":
		return a.count
	case "sum":
		return a.sum // NULL if no non-NULL inputs
	case "avg":
		if a.count == 0 {
			return nil
		}
		return toFloat(a.sum) / float64(a.count)
	default:
		return a.best
	}
}

func add(a, b Value) Value {
	if a == nil {
		return b
	}
	ai, aInt := a.(int64)
	bi, bInt := b.(int64)
	if aInt && bInt {
		return ai + bi
	}
	return toFloat(a) + toFloat(b)
}

// ---------------------------------------------------------------------------------------------
// HashAggregate
// ---------------------------------------------------------------------------------------------

// HashAggregate: output rows are group-by values followed by aggregate results, in the order each
// group was first seen (deterministic, unlike ranging over a Go map).
type HashAggregate struct {
	Child   Operator
	GroupBy []int
	Aggs    []AggSpec
	Names   []string

	MaxGroups int // groups held in memory at once = the operator's memory footprint

	out sliceOp
}

type group struct {
	key  []Value
	accs []*acc
}

func newGroup(key []Value, specs []AggSpec) *group {
	g := &group{key: key}
	for _, s := range specs {
		g.accs = append(g.accs, &acc{fn: s.Fn})
	}
	return g
}

func (g *group) step(r Row, specs []AggSpec) {
	for i, s := range specs {
		if s.Col < 0 {
			g.accs[i].step(nil, true)
		} else {
			g.accs[i].step(r[s.Col], false)
		}
	}
}

func (g *group) row() Row {
	out := append(Row{}, g.key...)
	for _, a := range g.accs {
		out = append(out, a.result())
	}
	return out
}

func (h *HashAggregate) Schema() []string  { return h.Names }
func (h *HashAggregate) Close()            {}
func (h *HashAggregate) Next() (Row, bool) { return h.out.Next() }

func (h *HashAggregate) Open() {
	// EXERCISE(hash-aggregate): Read the whole child. Find or create each row's group in a hash table (remembering first-seen order) and step its accumulators; then emit one row per group. No GROUP BY over empty input still yields one row.
	panic("TODO: exercise hash-aggregate")
}

// ---------------------------------------------------------------------------------------------
// SortAggregate
// ---------------------------------------------------------------------------------------------

// SortAggregate requires its input sorted on GroupBy. It streams: one group in memory, emitted
// when the next row's key differs.
type SortAggregate struct {
	Child   Operator
	GroupBy []int
	Aggs    []AggSpec
	Names   []string

	MaxGroups int // always 1 (that's the point)

	cur     *group
	curKey  string
	done    bool
	emitted bool
}

func (s *SortAggregate) Schema() []string { return s.Names }
func (s *SortAggregate) Close()           { s.Child.Close() }
func (s *SortAggregate) Open() {
	s.Child.Open()
	s.cur, s.done, s.emitted = nil, false, false
}

func (s *SortAggregate) Next() (Row, bool) {
	for !s.done {
		r, ok := s.Child.Next()
		if !ok {
			s.done = true
			break
		}
		key := make([]Value, len(s.GroupBy))
		for i, c := range s.GroupBy {
			key[i] = r[c]
		}
		k := groupKey(key)
		if s.cur != nil && k != s.curKey { // key changed: the previous group is complete
			finished := s.cur
			s.cur, s.curKey = newGroup(key, s.Aggs), k
			s.cur.step(r, s.Aggs)
			s.emitted = true
			return finished.row(), true
		}
		if s.cur == nil {
			s.cur, s.curKey, s.MaxGroups = newGroup(key, s.Aggs), k, 1
		}
		s.cur.step(r, s.Aggs)
	}
	// Input exhausted: flush the last group (or the single empty-input row with no GROUP BY).
	if s.cur != nil {
		last := s.cur
		s.cur = nil
		return last.row(), true
	}
	if !s.emitted && len(s.GroupBy) == 0 {
		s.emitted = true
		return newGroup(nil, s.Aggs).row(), true
	}
	return nil, false
}

// ---------------------------------------------------------------------------------------------
// Sorting
// ---------------------------------------------------------------------------------------------

// SortKey is one ORDER BY term.
type SortKey struct {
	Col  int
	Desc bool
}

// CompareRows orders rows by keys. NULLs sort last in both directions (DESIGN.md).
func CompareRows(a, b Row, keys []SortKey) int {
	for _, k := range keys {
		x, y := a[k.Col], b[k.Col]
		var c int
		switch {
		case x == nil && y == nil:
			c = 0
		case x == nil:
			return 1 // NULL last, regardless of Desc
		case y == nil:
			return -1
		default:
			c = Compare(x, y)
			if k.Desc {
				c = -c
			}
		}
		if c != 0 {
			return c
		}
	}
	return 0
}

// Sort reads everything, sorts in memory (stable), and hands rows back.
type Sort struct {
	Child Operator
	Keys  []SortKey
	out   sliceOp
}

func (s *Sort) Schema() []string  { return s.Child.Schema() }
func (s *Sort) Close()            {}
func (s *Sort) Next() (Row, bool) { return s.out.Next() }
func (s *Sort) Open() {
	rows := Collect(s.Child)
	sort.SliceStable(rows, func(i, j int) bool { return CompareRows(rows[i], rows[j], s.Keys) < 0 })
	s.out = sliceOp{cols: s.Child.Schema(), rows: rows}
}

// ExternalSort pretends memory holds only RunSize rows. Phase 1 fills memory, sorts it, and
// "spills" it as a sorted run (here: kept in a slice, standing in for a temp file). Phase 2 merges
// all runs at once with a min-heap holding one row per run — memory = number of runs, not rows.
type ExternalSort struct {
	Child   Operator
	Keys    []SortKey
	RunSize int

	Runs             int // how many sorted runs were spilled
	MergeComparisons int

	runs [][]Row
	pos  []int // next unread index in each run
	h    *mergeHeap
}

func (e *ExternalSort) Schema() []string { return e.Child.Schema() }
func (e *ExternalSort) Close()           { e.runs = nil }

func (e *ExternalSort) Open() {
	// Phase 1: produce sorted runs.
	e.runs = nil
	buf := []Row{}
	spill := func() {
		if len(buf) == 0 {
			return
		}
		sort.SliceStable(buf, func(i, j int) bool { return CompareRows(buf[i], buf[j], e.Keys) < 0 })
		e.runs = append(e.runs, buf)
		buf = []Row{}
	}
	e.Child.Open()
	for {
		r, ok := e.Child.Next()
		if !ok {
			break
		}
		buf = append(buf, r)
		if len(buf) == e.RunSize {
			spill()
		}
	}
	e.Child.Close()
	spill()
	e.Runs = len(e.runs)

	// Phase 2: seed the heap with the head of every run.
	e.pos = make([]int, len(e.runs))
	e.h = &mergeHeap{keys: e.Keys, cmps: &e.MergeComparisons}
	for i, run := range e.runs {
		heap.Push(e.h, cursor{run: i, row: run[0]})
		e.pos[i] = 1
	}
}

func (e *ExternalSort) Next() (Row, bool) {
	// EXERCISE(external-sort-merge): The heap holds the smallest unread row of every run. Pop the smallest, refill the heap from the run it came from, and return it.
	panic("TODO: exercise external-sort-merge")
}

type cursor struct {
	run int
	row Row
}

// mergeHeap is a min-heap of run heads. Ties break on run index, which keeps the merge stable.
type mergeHeap struct {
	items []cursor
	keys  []SortKey
	cmps  *int
}

func (h *mergeHeap) Len() int { return len(h.items) }
func (h *mergeHeap) Less(i, j int) bool {
	*h.cmps++
	if c := CompareRows(h.items[i].row, h.items[j].row, h.keys); c != 0 {
		return c < 0
	}
	return h.items[i].run < h.items[j].run
}
func (h *mergeHeap) Swap(i, j int) { h.items[i], h.items[j] = h.items[j], h.items[i] }
func (h *mergeHeap) Push(x any)    { h.items = append(h.items, x.(cursor)) }
func (h *mergeHeap) Pop() any {
	last := h.items[len(h.items)-1]
	h.items = h.items[:len(h.items)-1]
	return last
}

// TopN is ORDER BY … LIMIT N without sorting everything: keep a heap of the N best rows seen so
// far, with the *worst* of them on top so it can be evicted in O(log N).
type TopN struct {
	Child Operator
	Keys  []SortKey
	N     int

	Evictions int // rows that entered the heap and were later pushed out

	out sliceOp
}

type seqRow struct {
	seq int // arrival order: makes ties stable
	row Row
}

type worstFirst struct {
	items []seqRow
	keys  []SortKey
}

func (w *worstFirst) cmp(a, b seqRow) int {
	if c := CompareRows(a.row, b.row, w.keys); c != 0 {
		return c
	}
	return a.seq - b.seq
}
func (w *worstFirst) Len() int           { return len(w.items) }
func (w *worstFirst) Less(i, j int) bool { return w.cmp(w.items[i], w.items[j]) > 0 } // max-heap
func (w *worstFirst) Swap(i, j int)      { w.items[i], w.items[j] = w.items[j], w.items[i] }
func (w *worstFirst) Push(x any)         { w.items = append(w.items, x.(seqRow)) }
func (w *worstFirst) Pop() any {
	last := w.items[len(w.items)-1]
	w.items = w.items[:len(w.items)-1]
	return last
}

func (t *TopN) Schema() []string  { return t.Child.Schema() }
func (t *TopN) Close()            {}
func (t *TopN) Next() (Row, bool) { return t.out.Next() }
func (t *TopN) Open() {
	// EXERCISE(top-n): Keep only the best N rows seen so far in a heap with the worst on top; a better row replaces the top (count Evictions). At the end, sort what's left for output.
	panic("TODO: exercise top-n")
}
