;; Generated by lk exercises from clojure/test/lesson05/indexes_test.clj. DO NOT EDIT;
;; edit the reference lesson and regenerate. Fill in the TODOs here.

(ns exercises.lesson05.indexes-test
  (:require [clojure.test :refer [deftest is]]
            [exercises.lesson05.btree :as bt]
            [exercises.lesson05.indexes :as ix]))

(defn- leaf-depths [tree]
  (letfn [(walk [id d] (let [n (get-in tree [:nodes id])]
                         (if (:leaf? n) [d] (mapcat #(walk % (inc d)) (:children n)))))]
    (set (walk (:root tree) 0))))

(deftest btree-invariants
  (doseq [order [3 4 5 32]]
    (let [ks   (shuffle (range 500))
          tree (reduce (fn [t k] (bt/insert t k (* 10 k))) (bt/empty-tree order) ks)]
      (is (= 1 (count (leaf-depths tree))) "all leaves at the same depth")
      (is (every? #(<= (count (:keys %)) (dec order)) (vals (:nodes tree))))
      (is (= (range 500) (map first (:entries (bt/range-search tree nil nil)))) "leaf chain is sorted")
      (is (= [420] (:row-ids (bt/search tree 42))))
      (is (= [] (:row-ids (bt/search tree 9999))))
      (is (= (range 100 111) (map first (:entries (bt/range-search tree 100 110))))))))

(deftest duplicates-and-nulls
  (let [tree (-> (bt/empty-tree 3) (bt/insert 5 0) (bt/insert 5 1) (bt/insert nil 2) (bt/insert 7 3))]
    (is (= [0 1] (:row-ids (bt/search tree 5))))
    (is (= 2 (count (:entries (bt/range-search tree nil nil)))))))

(deftest index-operators
  (let [{:keys [customers orders]} (ix/generate)
        idx  (bt/build (:rows orders) 1 32)
        full (filter #(= 7 (nth % 1)) (:rows orders))
        k    (atom {})]
    (is (= (set full) (set (ix/run (ix/index-scan orders "o" idx 7 7 {:counters k})))))
    (is (= (count full) (:rows-read @k)))
    (let [seattle? #(= "Seattle" (nth % 2))
          h (ix/run (ix/hash-join (ix/filter-op (ix/scan customers "c") seattle?) (ix/scan orders "o") #(nth % 0) #(nth % 1)))
          i (ix/run (ix/index-nl-join (ix/filter-op (ix/scan customers "c") seattle?) orders "o" idx #(nth % 0)))]
      (is (= (set h) (set i))))))
