# /// script
# requires-python = ">=3.11"
# ///
"""Generate the exercise track from the reference lessons.

Mark a region inside a function body in the reference code:

  Go                                         Clojure
  // EXERCISE(hash-join-probe): hint text    ;; EXERCISE(hash-join-probe): hint text
  ...reference lines...                      ...reference forms (balanced)...
  // END EXERCISE                            ;; END EXERCISE

The hint may continue on following comment lines (`// ` / `;; `) before the code starts.

Output (overwritten every run; never edit by hand):
  go/exercises/lessonNN/            package lessonNN, tests copied; regions → panic("TODO: exercise …")
  clojure/ex/exercises/lessonNN/    ns exercises.lessonNN.*, tests copied; regions → (throw (ex-info "TODO: exercise …" {}))
  EXERCISES.md                      index: every exercise, its hint, where it lives, how to test it

Then checks: exercises compile, their tests FAIL (something is actually missing), and the reference
tests PASS. Run:  uv run tools/make_exercises.py [--no-check]
"""
import json, re, shutil, subprocess, sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
GO, CLJ = ROOT / "go", ROOT / "clojure"
POSTS = {f"{i:02d}": p for i, p in enumerate(["", "01-expressions", "02-iterators", "03-joins", "04-aggregation",
                                              "05-indexes", "06-planner", "07-bytecode"]) if p}
START = re.compile(r"^(\s*)(//|;;)\s*EXERCISE\(([\w-]+)\):\s*(.*)$")
END = re.compile(r"^\s*(//|;;)\s*END EXERCISE\s*$")


def strip(text, lang, where):
    """Replace marked regions. Returns (new_text, [exercise dicts])."""
    out, found, lines, i = [], [], text.split("\n"), 0
    while i < len(lines):
        m = START.match(lines[i])
        if not m:
            if END.match(lines[i]):
                sys.exit(f"{where}:{i+1}: END EXERCISE without EXERCISE")
            out.append(lines[i]); i += 1; continue
        indent, cm, ex_id, hint = m.group(1), m.group(2), m.group(3), [m.group(4).strip()]
        j = i + 1
        while j < len(lines) and lines[j].strip().startswith(cm) and not END.match(lines[j]):
            hint.append(lines[j].strip()[len(cm):].strip()); j += 1
        k = j
        while k < len(lines) and not END.match(lines[k]):
            if START.match(lines[k]):
                sys.exit(f"{where}:{k+1}: nested EXERCISE")
            k += 1
        if k == len(lines):
            sys.exit(f"{where}:{i+1}: EXERCISE({ex_id}) has no END EXERCISE")
        hint_text = " ".join(h for h in hint if h)
        out.append(f"{indent}{cm} EXERCISE({ex_id}): {hint_text}")
        if lang == "go":
            out.append(f'{indent}panic("TODO: exercise {ex_id}")')
        else:
            out.append(f'{indent}(throw (ex-info "TODO: exercise {ex_id}" {{:exercise "{ex_id}"}}))')
        found.append({"id": ex_id, "hint": hint_text, "lines": k - j})
        i = k + 1
    return "\n".join(out), found


def go_unused_imports(pkg_dir):
    """Delete imports the stripped code no longer uses (Go refuses to compile otherwise)."""
    for _ in range(5):
        r = subprocess.run(["go", "build", "./" + str(pkg_dir.relative_to(GO))], cwd=GO, capture_output=True, text=True)
        bad = re.findall(r'^(.+?\.go):(\d+):\d+: "([^"]+)" imported and not used', r.stderr, re.M)
        if not bad:
            return r
        for f, line, _ in bad:
            p = GO / f if not Path(f).is_absolute() else Path(f)
            ls = p.read_text().split("\n")
            ls[int(line) - 1] = ""
            p.write_text("\n".join(ls))
    return r


def gen_go():
    dest_root = GO / "exercises"
    shutil.rmtree(dest_root, ignore_errors=True)
    index = []
    for src in sorted(GO.glob("lesson0[1-7]")):
        n = src.name[-2:]
        dest = dest_root / src.name
        dest.mkdir(parents=True)
        for f in sorted(src.glob("*.go")):
            text = f.read_text()
            if not f.name.endswith("_test.go"):
                text, found = strip(text, "go", f.relative_to(ROOT))
                index += [{**e, "lang": "Go", "lesson": n, "file": f"go/exercises/{src.name}/{f.name}"} for e in found]
            text = text.replace(f'"execengine/{src.name}"', f'"execengine/exercises/{src.name}"')
            (dest / f.name).write_text(f"// Code generated by tools/make_exercises.py from go/{src.name}/{f.name}. DO NOT EDIT;\n// edit the reference lesson and regenerate. Fill in the TODOs here.\n\n" + text)
        r = go_unused_imports(dest)
        if r.returncode != 0:
            print(r.stderr); sys.exit(f"go/exercises/{src.name} does not compile")
    return index


def gen_clj():
    dest_root = CLJ / "ex"
    shutil.rmtree(dest_root, ignore_errors=True)
    index = []
    for kind, base in (("src", CLJ / "src"), ("test", CLJ / "test")):
        for src in sorted(base.glob("lesson0[1-7]")):
            n = src.name[-2:]
            for f in sorted(src.rglob("*.clj")):
                text = f.read_text()
                if kind == "src":
                    text, found = strip(text, "clj", f.relative_to(ROOT))
                    index += [{**e, "lang": "Clojure", "lesson": n,
                               "file": f"clojure/ex/exercises/{src.name}/{f.relative_to(src)}"} for e in found]
                # lesson03.joins → exercises.lesson03.joins (ns names, requires, fully qualified refs)
                text = re.sub(r"(?<![\w.\-])lesson0([1-7])\.", r"exercises.lesson0\1.", text)
                out = dest_root / "exercises" / src.name / f.relative_to(src)
                out.parent.mkdir(parents=True, exist_ok=True)
                out.write_text(f";; Generated by tools/make_exercises.py from clojure/{kind}/{src.name}/{f.relative_to(src)}. DO NOT EDIT;\n;; edit the reference lesson and regenerate. Fill in the TODOs here.\n\n" + text)
    return index


def write_index(index):
    by = {}
    for e in index:
        by.setdefault(e["lesson"], []).append(e)
    md = ["# Exercises", "",
          "Each lesson's key functions, with their bodies removed. Read the post, then make the tests pass.",
          "Generated by `uv run tools/make_exercises.py` from markers in the reference lessons: don't edit",
          "the generated files' structure, just fill in the TODOs. Peeking at `go/lessonNN` or",
          "`clojure/src/lessonNN` is the answer key.", "",
          "```bash",
          "cd go && go test ./exercises/lesson03/                 # Go",
          "cd clojure && clojure -M:ex -d ex -n exercises.lesson03.joins-test   # Clojure",
          "```", ""]
    for n in sorted(by):
        post = POSTS[n]
        md += [f"## Part {int(n)} · [{post.split('-', 1)[1].title()}](docs/posts/{post}.html)", ""]
        for e in by[n]:
            md.append(f"- **`{e['id']}`** ({e['lang']}, `{e['file']}`, {e['lines']} lines): {e['hint']}")
        md.append("")
    (ROOT / "EXERCISES.md").write_text("\n".join(md))
    # The site links to its own copy (GitHub Pages renders it; it can't reach files outside docs/).
    (ROOT / "docs/EXERCISES.md").write_text("\n".join(md).replace("](docs/posts/", "](posts/"))
    (ROOT / "docs/assets/exercises.js").write_text("window.EE_EXERCISES = " + json.dumps(index, indent=1) + ";\n")


def check(index):
    ok = True
    r = subprocess.run(["go", "test", "./lesson0..."], cwd=GO, capture_output=True, text=True)
    print("reference go tests:", "PASS" if r.returncode == 0 else "FAIL"); ok &= r.returncode == 0
    for d in sorted((GO / "exercises").glob("lesson0*")):
        has = any(e["lang"] == "Go" and e["lesson"] == d.name[-2:] for e in index)
        r = subprocess.run(["go", "test", f"./exercises/{d.name}/"], cwd=GO, capture_output=True, text=True)
        status = "fails as expected" if r.returncode != 0 else ("PASSES — exercise tests don't catch the TODOs!" if has else "no exercises")
        if has and r.returncode == 0: ok = False
        if "build failed" in r.stdout + r.stderr or "[setup failed]" in r.stdout: status = "DOES NOT COMPILE"; ok = False
        print(f"go exercises/{d.name}: {status}")
    r = subprocess.run(["clojure", "-M:ex", "-d", "ex"], cwd=CLJ, capture_output=True, text=True)
    tail = (r.stdout + r.stderr).strip().splitlines()[-3:]
    compiled = "Syntax error" not in r.stdout + r.stderr and "Could not locate" not in r.stdout + r.stderr
    print("clojure exercises:", "fail as expected" if r.returncode != 0 and compiled else ("DOES NOT LOAD" if not compiled else "PASS — tests don't catch TODOs!"), "|", " ".join(tail))
    ok &= r.returncode != 0 and compiled
    return ok


if __name__ == "__main__":
    index = gen_go() + gen_clj()
    write_index(index)
    print(f"{len(index)} exercises:", ", ".join(f"{e['lang'][0]}{e['lesson']}:{e['id']}" for e in index) or "none yet")
    if "--no-check" not in sys.argv and index:
        sys.exit(0 if check(index) else 1)
