;; Generated by tools/make_exercises.py from clojure/test/lesson07/bytecode_test.clj. DO NOT EDIT;
;; edit the reference lesson and regenerate. Fill in the TODOs here.

(ns exercises.lesson07.bytecode-test
  (:require [clojure.test :refer [deftest is]]
            [exercises.lesson07.bytecode :as b]
            [exercises.lesson07.compiler :as c]
            [exercises.lesson07.vm :as vm]))

(defn- run [plan] (vm/run-all (:program (c/compile-plan plan b/toy-db)) b/toy-db))

(def scan-c {:op :scan :table "customers" :alias "c"})
(def scan-o {:op :scan :table "orders" :alias "o"})

(deftest simple
  (is (= [["Ada" 36]] (run b/simple-plan)))
  (is (= [["Ada" 36] ["Cy" 52]] (run (assoc b/simple-plan :n 5)))))

(deftest report
  (is (= [["Cy" 1 5] ["Ada" 2 3] ["Di" 1 1]] (run b/report-plan))))

(deftest nl-join-and-expressions
  (is (= [["Ada" 10 4] ["Ada" 11 2] ["Cy" 12 10] ["Di" 13 2]]
         (run {:op :project
               :items [[[:col "c.name"] "name"] [[:col "o.id"] "order"] [[:* [:col "o.qty"] [:lit 2]] "dbl"]]
               :child {:op :nl-join :left scan-c :right scan-o :pred [:= [:col "c.id"] [:col "o.customer_id"]]}}))))

(deftest aggregate-without-group-on-empty-input
  (is (= [[0 nil]]
         (run {:op :aggregate :group [] :aggs [{:fn "count" :arg :* :name "n"} {:fn "sum" :arg [:col "c.age"] :name "s"}]
               :child {:op :filter :pred [:> [:col "c.age"] [:lit 1000]] :child scan-c}}))))

(deftest null-semantics-in-the-vm
  (is (= [["Bo"]]
         (run {:op :project :items [[[:col "c.name"] "n"]]
               :child {:op :filter :pred [:is-null [:col "c.age"]] :child scan-c}})))
  (is (= [[18.0] [nil]]
         (run {:op :project :items [[[:/ [:col "c.age"] [:lit 2]] "x"]] :child
               {:op :limit :n 2 :child {:op :filter :pred [:< [:col "c.id"] [:lit 3]] :child scan-c}}})))
  (is (= [[nil]] (run {:op :project :items [[[:/ [:col "c.id"] [:lit 0]] "x"]] :child {:op :limit :n 1 :child scan-c}}))))

(deftest snapshot-at-every-instruction
  (let [{:keys [program]} (c/compile-plan b/report-plan b/toy-db)
        expected (vm/run-all program b/toy-db)]
    ;; pause after every single instruction, round-trip through EDN, continue
    (is (= expected
           (loop [s (vm/new-state) rows []]
             (let [{:keys [state row status]} (vm/resume s program b/toy-db 1)
                   state (vm/restore (vm/snapshot state))]
               (case status :row (recur state (conj rows row)) :out-of-fuel (recur state rows) :done rows)))))))
