;; Generated by tools/make_exercises.py from clojure/src/lesson07/vm.clj. DO NOT EDIT;
;; edit the reference lesson and regenerate. Fill in the TODOs here.

(ns exercises.lesson07.vm
  "A register virtual machine for query plans, modeled on SQLite's VDBE.

  A program is a vector of instructions — plain maps:

      {:op :Column :p1 0 :p2 3 :p3 7 :comment \"r[7] = c.age\"}

  The machine's ENTIRE state is one plain map:

      {:pc 12                                   next instruction
       :regs {3 36, 7 \"Ada\"}                  register file (sparse)
       :cursors {0 {:table \"customers\" :pos 2}}   a table cursor is just a position
       :hash {0 {:buckets {1 [[…]]} :match {…}}}  hash-join build tables
       :sorters {…} :aggs {…}                    ORDER BY buffers, GROUP BY accumulators
       :steps 140 :halted false}

  `step` is a function from state to state: it executes ONE instruction. `resume` calls step until
  the program emits a row (ResultRow), halts, or runs out of fuel — then simply returns. Nothing
  lives on the Clojure call stack between calls, so pausing is free, and because the state is a
  value it can be printed, saved, sent somewhere else, read back, and resumed. The tables
  themselves (`db`) are immutable inputs and not part of the state: a cursor is just {table, pos}."
  (:require [clojure.edn :as edn]
            [clojure.string :as str]))

;;; ------------------------------------------------------------------------------------------------
;;; Value semantics (DESIGN.md)

(defn compare-values [a b]
  (if (and (number? a) (number? b))
    (if (and (int? a) (int? b)) (compare (long a) (long b)) (compare (double a) (double b)))
    (compare a b)))

(defn- arith [op a b]
  (cond (or (nil? a) (nil? b)) nil
        (= op :Div) (if (zero? (double b)) nil (/ (double a) (double b)))
        :else (let [f ({:Add + :Sub - :Mul *} op)]
                (if (and (int? a) (int? b)) (f a b) (f (double a) (double b))))))

(defn- cmp [op a b]
  (when (and (some? a) (some? b))
    (let [c (compare-values a b)]
      (case op :Eq (zero? c) :Ne (not (zero? c)) :Lt (neg? c) :Le (<= c 0) :Gt (pos? c) :Ge (>= c 0)))))

(defn- call-fn [fname args]
  (if (= fname "coalesce")
    (first (remove nil? args))
    (when-let [x (first args)]
      (case fname
        "lower" (str/lower-case x) "upper" (str/upper-case x) "length" (long (count x))
        "abs" (if (int? x) (Math/abs (long x)) (Math/abs (double x)))))))

(defn- sort-cmp
  "Compare two sorter rows by spec [[col-idx :asc|:desc] …], NULLs last either way."
  [spec a b]
  (reduce (fn [_ [i dir]]
            (let [x (nth a i) y (nth b i)
                  c (cond (and (nil? x) (nil? y)) 0 (nil? x) 1 (nil? y) -1
                          :else (cond-> (compare-values x y) (= dir :desc) -))]
              (if (zero? c) 0 (reduced c))))
          0 spec))

;;; Aggregate accumulators — plain data too

(defn- acc-step [acc v]
  (if (nil? v)
    acc
    (-> acc
        (update :count inc)
        (update :sum #(cond (nil? %) v (and (int? %) (int? v)) (+ % v) :else (+ (double %) (double v))))
        (update :min #(if (or (nil? %) (neg? (compare-values v %))) v %))
        (update :max #(if (or (nil? %) (pos? (compare-values v %))) v %)))))

(defn- acc-finish [fname {:keys [count sum min max]}]
  (case fname "count" count "sum" sum "min" min "max" max
        "avg" (when (pos? count) (/ (double sum) count))))

(def ^:private empty-acc {:count 0 :sum nil :min nil :max nil})

;;; ------------------------------------------------------------------------------------------------
;;; The machine

(defn new-state
  "A fresh VM state, positioned at instruction 0."
  []
  {:pc 0 :regs {} :cursors {} :hash {} :sorters {} :aggs {} :steps 0 :halted false})

(defn- reg [s r] (get-in s [:regs r]))
(defn- set-reg [s r v] (assoc-in s [:regs r] v))
(defn- jump [s addr] (assoc s :pc addr))
(defn- table-rows [db cursor] (:rows (db (:table cursor))))

(defn step
  "Execute the instruction at :pc. Returns the next state. A ResultRow puts the output row under
  :out (the caller takes it off)."
  [s program db]
  (let [{:keys [op p1 p2 p3 p4]} (nth program (:pc s))
        s (-> s (update :pc inc) (update :steps inc))]  ; default: fall through to the next instruction
    (case op
      :Init         (jump s p2)
      :Goto         (jump s p2)
      :Halt         (assoc s :halted true)

      ;; --- table cursors
      :OpenScan     (assoc-in s [:cursors p1] {:table p4 :pos 0})
      :Rewind       (let [s (assoc-in s [:cursors p1 :pos] 0)]
                      (if (empty? (table-rows db (get-in s [:cursors p1]))) (jump s p2) s))
      :Next         (let [s (update-in s [:cursors p1 :pos] inc)
                          c (get-in s [:cursors p1])]
                      (if (< (:pos c) (count (table-rows db c))) (jump s p2) s))
      :Column       (let [c (get-in s [:cursors p1])]
                      (set-reg s p3 (nth (nth (table-rows db c) (:pos c)) p2)))

      ;; --- registers and expressions
      (:Integer :Const) (set-reg s p2 p4)
      :Null         (set-reg s p2 nil)
      :Copy         (set-reg s p2 (reg s p1))
      (:Add :Sub :Mul :Div) (set-reg s p3 (arith op (reg s p1) (reg s p2)))
      (:Eq :Ne :Lt :Le :Gt :Ge)          (set-reg s p3 (cmp op (reg s p1) (reg s p2)))
      :And          (let [a (reg s p1) b (reg s p2)]
                      (set-reg s p3 (cond (or (false? a) (false? b)) false (or (nil? a) (nil? b)) nil :else true)))
      :Or           (let [a (reg s p1) b (reg s p2)]
                      (set-reg s p3 (cond (or (true? a) (true? b)) true (or (nil? a) (nil? b)) nil :else false)))
      :Not          (set-reg s p3 (let [a (reg s p1)] (when (some? a) (not a))))
      :IsNull       (set-reg s p3 (nil? (reg s p1)))
      :NotNull      (set-reg s p3 (some? (reg s p1)))
      :Func         (set-reg s p3 (call-fn p4 (mapv #(reg s %) (range p1 (+ p1 p2)))))

      ;; --- control flow
      :IfNot        (if (true? (reg s p1)) s (jump s p2))
      :If           (if (true? (reg s p1)) (jump s p2) s)
      :DecrJumpZero (let [s (update-in s [:regs p1] dec)] (if (zero? (reg s p1)) (jump s p2) s))
      :ResultRow
      ;; EXERCISE(vm-result-row): Hand a row to the caller: put the values of registers p1 .. p1+p2-1 under :out. (pc has already moved past this instruction, so resuming continues after it.)
      (throw (ex-info "TODO: exercise vm-result-row" {:exercise "vm-result-row"}))

      ;; --- hash join: build a table, then seek + iterate matches
      :HashOpen     (assoc-in s [:hash p1] {:buckets {} :match nil})
      :HashInsert   (let [k (reg s p2)]
                      (if (nil? k) s
                          (update-in s [:hash p1 :buckets k] (fnil conj []) (mapv #(reg s %) (range p3 (+ p3 p4))))))
      :HashSeek     (let [k (reg s p2) bucket (when (some? k) (get-in s [:hash p1 :buckets k]))]
                      (if (seq bucket) (assoc-in s [:hash p1 :match] {:key k :i 0}) (jump s p3)))
      :HashNext     (let [{:keys [key i]} (get-in s [:hash p1 :match])
                          n (count (get-in s [:hash p1 :buckets key]))]
                      (if (< (inc i) n) (jump (assoc-in s [:hash p1 :match :i] (inc i)) p2) s))
      :HashColumn   (let [{:keys [key i]} (get-in s [:hash p1 :match])]
                      (set-reg s p3 (nth (get-in s [:hash p1 :buckets key i]) p2)))

      ;; --- sorter: buffer rows, sort once, iterate
      :SorterOpen   (assoc-in s [:sorters p1] {:spec p4 :rows [] :pos 0})
      :SorterInsert (update-in s [:sorters p1 :rows] conj (mapv #(reg s %) (range p2 (+ p2 p3))))
      :SorterSort   (let [{:keys [spec rows]} (get-in s [:sorters p1])
                          s (-> s (assoc-in [:sorters p1 :rows] (vec (sort #(sort-cmp spec %1 %2) rows)))
                                (assoc-in [:sorters p1 :pos] 0))]
                      (if (empty? rows) (jump s p2) s))
      :SorterNext   (let [s (update-in s [:sorters p1 :pos] inc) {:keys [pos rows]} (get-in s [:sorters p1])]
                      (if (< pos (count rows)) (jump s p2) s))
      :SorterColumn (let [{:keys [pos rows]} (get-in s [:sorters p1])] (set-reg s p3 (nth (nth rows pos) p2)))

      ;; --- aggregation: groups in first-seen order
      :AggOpen      (assoc-in s [:aggs p1] {:spec p4 :index {} :groups [] :pos 0})
      :AggStep      (let [{:keys [spec index groups]} (get-in s [:aggs p1])
                          k   (mapv #(reg s %) (range p2 (+ p2 p3)))
                          gi  (get index k (count groups))
                          accs (get-in groups [gi 1] (vec (repeat (count (:fns spec)) empty-acc)))
                          accs (vec (map-indexed (fn [j acc] (acc-step acc (reg s (+ p4 j)))) accs))]
                      (-> s (assoc-in [:aggs p1 :index k] gi) (assoc-in [:aggs p1 :groups gi] [k accs])))
      :AggRewind    (let [{:keys [spec groups]} (get-in s [:aggs p1])
                          ;; no GROUP BY: empty input still yields one row
                          s (if (and (empty? groups) (zero? (:nkeys spec)))
                              (assoc-in s [:aggs p1 :groups] [[[] (vec (repeat (count (:fns spec)) empty-acc))]])
                              s)
                          s (assoc-in s [:aggs p1 :pos] 0)]
                      (if (empty? (get-in s [:aggs p1 :groups])) (jump s p2) s))
      :AggNext      (let [s (update-in s [:aggs p1 :pos] inc) {:keys [pos groups]} (get-in s [:aggs p1])]
                      (if (< pos (count groups)) (jump s p2) s))
      :AggColumn    (let [{:keys [spec pos groups]} (get-in s [:aggs p1])
                          [k accs] (nth groups pos)
                          nk (count k)]
                      (set-reg s p3 (if (< p2 nk) (nth k p2)
                                        (acc-finish (nth (:fns spec) (- p2 nk)) (nth accs (- p2 nk)))))))))

(defn resume
  "Run from `state` for at most `fuel` instructions. Returns {:state :row :status} where status is
  :row (a row was produced; call again to continue), :done, or :out-of-fuel (call again with more
  fuel). The returned state is the whole story — keep it, print it, save it."
  [state program db fuel]
  ;; EXERCISE(vm-step-loop): Call `step` repeatedly. Stop with :done once halted, :out-of-fuel after `fuel` instructions, or :row as soon as a step leaves a row under :out (remove it from the returned state).
  (throw (ex-info "TODO: exercise vm-step-loop" {:exercise "vm-step-loop"}))
  )

(defn run-all
  "Run a program to completion; return its rows."
  [program db]
  (loop [s (new-state) rows []]
    (let [{:keys [state row status]} (resume s program db Long/MAX_VALUE)]
      (if (= status :row) (recur state (conj rows row)) rows))))

(defn snapshot
  "Serialize a VM state. It's already plain data, so this is just pr-str."
  [state]
  (pr-str state))

(defn restore
  "Read a snapshot back into a state that `resume` can continue from."
  [s]
  (edn/read-string s))

(defn listing
  "Render a program like SQLite's EXPLAIN: addr, opcode, p1..p4, comment."
  [program]
  (str/join "\n"
            (cons (format "%-4s  %-13s %4s %4s %4s  %-22s %s" "addr" "opcode" "p1" "p2" "p3" "p4" "comment")
                  (map-indexed (fn [i {:keys [op p1 p2 p3 p4 comment]}]
                                 (format "%-4d  %-13s %4s %4s %4s  %-22s %s" i (name op)
                                         (or p1 "") (or p2 "") (or p3 "")
                                         (if (nil? p4) "" (let [s (pr-str p4)] (if (> (count s) 22) (str (subs s 0 19) "...") s)))
                                         (or comment "")))
                               program))))
